#!/bin/bash

/usr/sbin/mysqld &
PID=`jobs -p`
trap "kill -SIGQUIT $PID" EXIT

sleep 2

cat <<-EOF | mysql && echo "mysql updated!" || echo "mysql was not updated"
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
EOF

